- .github/workflows/.build.yml
- .github/workflows/build-buildx.yml
- .github/workflows/build-compose.yml
- .github/workflows/build-containerd.yml
- .github/workflows/build-credential-helpers.yml
- .github/workflows/build-docker-cli.yml
- .github/workflows/build-docker-engine.yml
- .github/workflows/build-sbom.yml
- .github/workflows/build-scan.yml
- common/build.mk
- common/vars.mk
> split pkgs and limit platforms for testing

- .github/workflows/.build.yml
- .github/workflows/build-buildx.yml
- .github/workflows/build-compose.yml
- .github/workflows/build-containerd.yml
- .github/workflows/build-credential-helpers.yml
- .github/workflows/build-docker-cli.yml
- .github/workflows/build-docker-engine.yml
- .github/workflows/build-sbom.yml
- .github/workflows/build-scan.yml
> ci: test release target

- .github/workflows/.build.yml
- .github/workflows/release.yml
- pkg/buildx/docker-bake.hcl
- pkg/compose/docker-bake.hcl
- pkg/containerd/docker-bake.hcl
- pkg/credential-helpers/docker-bake.hcl
- pkg/docker-cli/docker-bake.hcl
- pkg/docker-engine/docker-bake.hcl
- pkg/sbom/docker-bake.hcl
- pkg/scan/docker-bake.hcl
> switch to dockereng/packaging

- .github/workflows/release.yml
> ci(release): change package input to choice type

- .github/workflows/.build.yml
- .github/workflows/release.yml
- README.md
- common/build.mk
- pkg/buildx/Makefile
- pkg/buildx/docker-bake.hcl
- pkg/buildx/verify.Dockerfile
- pkg/compose/Makefile
- pkg/compose/docker-bake.hcl
- pkg/compose/verify.Dockerfile
- pkg/containerd/Makefile
- pkg/containerd/docker-bake.hcl
- pkg/containerd/verify.Dockerfile
- pkg/credential-helpers/Makefile
- pkg/credential-helpers/docker-bake.hcl
- pkg/credential-helpers/verify.Dockerfile
- pkg/docker-cli/Makefile
- pkg/docker-cli/docker-bake.hcl
- pkg/docker-cli/verify.Dockerfile
- pkg/docker-engine/Dockerfile
- pkg/docker-engine/Makefile
- pkg/docker-engine/docker-bake.hcl
- pkg/docker-engine/verify.Dockerfile
- pkg/sbom/Makefile
- pkg/sbom/docker-bake.hcl
- pkg/sbom/verify.Dockerfile
- pkg/scan/Makefile
- pkg/scan/docker-bake.hcl
- pkg/scan/verify.Dockerfile
adds verify target for each project and a new step in ci workflow.
> pkg: verify target

- .github/workflows/.release.yml
- .github/workflows/release-buildx.yml
- .github/workflows/release-compose.yml
- .github/workflows/release-containerd.yml
- .github/workflows/release-credential-helpers.yml
- .github/workflows/release-docker-cli.yml
- .github/workflows/release-docker-engine.yml
- .github/workflows/release-sbom.yml
- .github/workflows/release-scan.yml
- pkg/buildx/Makefile
- pkg/compose/Makefile
- pkg/containerd/Makefile
- pkg/credential-helpers/Makefile
- pkg/docker-cli/Makefile
- pkg/docker-engine/Makefile
- pkg/sbom/Makefile
- pkg/scan/Makefile
> ci(release): split workflow and allow overriding repo/ref

- .github/workflows/.release.yml
- .github/workflows/release-buildx.yml
- .github/workflows/release-compose.yml
- .github/workflows/release-containerd.yml
- .github/workflows/release-credential-helpers.yml
- .github/workflows/release-docker-cli.yml
- .github/workflows/release-docker-engine.yml
- .github/workflows/release-sbom.yml
- .github/workflows/release-scan.yml
Build packages on a time-based schedule (every Sunday) using their respective default branch as ref.
> ci: nightly builds

- common/packages.mk
> common: fix supported platforms for centos7

- common/release.Dockerfile
> release: push metadata.env

- common/scripts/rpm-init.sh
> common: fix git version for ol7

- .github/workflows/.release.yml
> ci(release): verify packages

- .github/workflows/.release.yml
> ci(release): update gha matrix

- common/build.mk
> common: fix platform

- .github/workflows/.release.yml
> ci(release): update buildx action

- pkg/buildx/Makefile
- pkg/compose/Makefile
- pkg/containerd/Makefile
- pkg/credential-helpers/Makefile
- pkg/docker-cli/Makefile
- pkg/docker-engine/Makefile
- pkg/sbom/Makefile
- pkg/scan/Makefile
> pkg: set Go version according to each project

- pkg/scan/Makefile
> pkg(scan): update to 0.23.0

- pkg/containerd/Makefile
> pkg(containerd): update to 1.6.10

- pkg/compose/Makefile
> pkg(compose): update to 2.14.0

- .github/workflows/.build.yml
- .github/workflows/.release.yml
> ci: fix deprecated set-output gha syntax

- common/packages.hcl
- common/packages.mk
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
follow-up https://github.com/docker/docker-ce-packaging/pull/779
> deb: add ubuntu 22.10 kinetic

- pkg/compose/docker-bake.hcl
- pkg/containerd/docker-bake.hcl
- pkg/scan/docker-bake.hcl
> pkg: align scan, compose and containerd versions in bake def

- pkg/containerd/Dockerfile
- pkg/containerd/Makefile
- pkg/containerd/deb/changelog
- pkg/containerd/docker-bake.hcl
- pkg/containerd/rpm/containerd.spec
> pkg(containerd): update to 1.6.14

- common/packages.hcl
- common/packages.mk
follow-up https://github.com/docker/docker-ce-packaging/pull/800
> common: fedora 35 eol

- pkg/compose/Makefile
- pkg/compose/docker-bake.hcl
- relates to https://github.com/docker/docker-ce-packaging/pull/808
> pkg(compose): update to 2.15.1

- pkg/buildx/Makefile
- pkg/buildx/docker-bake.hcl
- relates to https://github.com/docker/docker-ce-packaging/pull/812
> pkg(buildx): update to 0.10.0

- .github/workflows/.build.yml
- .github/workflows/.release.yml
> ci: switch to org secrets to push to Docker Hub

- pkg/buildx/Dockerfile
- pkg/buildx/scripts/pkg-static-build.sh
> pkg(buildx): use "make build" for static build

- .github/workflows/build-containerd.yml
- .github/workflows/build-docker-cli.yml
- .github/workflows/build-docker-engine.yml
> ci: trigger build on release branches

- .github/workflows/build-buildx.yml
- .github/workflows/build-compose.yml
- .github/workflows/build-containerd.yml
- .github/workflows/build-credential-helpers.yml
- .github/workflows/build-docker-cli.yml
- .github/workflows/build-docker-engine.yml
- .github/workflows/build-sbom.yml
- .github/workflows/build-scan.yml
> ci: fix branch filter on push

- .github/workflows/.release.yml
> ci: fix metadata resolution

- .github/workflows/.release.yml
> ci: fix release version

- pkg/compose/Dockerfile
- pkg/compose/Makefile
- pkg/compose/docker-bake.hcl
- pkg/compose/scripts/pkg-static-build.sh
- pkg/docker-engine/Dockerfile
> pkg(compose): bump Go to 1.20.0

- pkg/containerd/deb/changelog
- pkg/containerd/rpm/containerd.spec
follow-up https://github.com/docker/containerd-packaging/pull/307
> pkg(containerd): update to 1.6.16

- .github/workflows/build-buildx.yml
- .github/workflows/build-compose.yml
- .github/workflows/build-containerd.yml
- .github/workflows/build-credential-helpers.yml
- .github/workflows/build-docker-cli.yml
- .github/workflows/build-docker-engine.yml
- .github/workflows/build-sbom.yml
- .github/workflows/build-scan.yml
> ci: set path filter on push

- pkg/buildx/Dockerfile
- pkg/buildx/verify.Dockerfile
- pkg/compose/Dockerfile
- pkg/compose/verify.Dockerfile
- pkg/containerd/Dockerfile
- pkg/containerd/verify.Dockerfile
- pkg/credential-helpers/Dockerfile
- pkg/credential-helpers/verify.Dockerfile
- pkg/docker-cli/Dockerfile
- pkg/docker-cli/verify.Dockerfile
- pkg/docker-engine/Dockerfile
- pkg/docker-engine/verify.Dockerfile
- pkg/sbom/Dockerfile
- pkg/sbom/verify.Dockerfile
- pkg/scan/Dockerfile
- pkg/scan/verify.Dockerfile
related to https://github.com/moby/buildkit/issues/3625
> update xx to 1.2.1

- Makefile
- common/packages.hcl
- common/packages.mk
follow-up https://github.com/docker/docker-ce-packaging/pull/838
> deb: add debian/raspbian 12 bookworm

- common/vars.mk
follow-up https://github.com/docker/docker-ce-packaging/pull/869
> common: update to go 1.20.2

- pkg/containerd/deb/changelog
- pkg/containerd/rpm/containerd.spec
follow-up:
* https://github.com/docker/containerd-packaging/pull/308
* https://github.com/docker/containerd-packaging/pull/310
* https://github.com/docker/containerd-packaging/pull/313
> [containerd/1.6] pkg(containerd): update to 1.6.20

- pkg/docker-cli/deb/control
- pkg/docker-cli/rpm/docker-ce-cli.spec
follow-up https://github.com/docker/docker-ce-packaging/pull/870
> pkg(docker-cli): remove scan plugin from recommends

- Makefile
- common/packages.hcl
- common/packages.mk
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
* follow-up https://github.com/docker/docker-ce-packaging/pull/875
> distro: add ubuntu 23.04

- Makefile
- common/packages.hcl
- common/packages.mk
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
backport of:
* https://github.com/docker/packaging/pull/88
* https://github.com/docker/packaging/pull/120
> [docker/23.0] update distros

- Makefile
- common/packages.hcl
- common/packages.mk
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
backport of:
* https://github.com/docker/packaging/pull/88
* https://github.com/docker/packaging/pull/120
> [containerd/1.6] update distros

- pkg/buildx/Makefile
- pkg/compose/Dockerfile
- pkg/compose/Makefile
- pkg/containerd/Makefile
- pkg/credential-helpers/Dockerfile
- pkg/credential-helpers/Makefile
follow-up https://github.com/docker/packaging/pull/78
> pkg(buildx,compose,containerd,cred-helpers): arm/v5 support

- Makefile
- common/packages.hcl
- common/packages.mk
* follow-up https://github.com/docker/docker-ce-packaging/pull/803
> distro: add fedora 38

- pkg/credential-helpers/Dockerfile
- pkg/credential-helpers/scripts/pkg-static-build.sh
follow-up https://github.com/docker/docker-credential-helpers/pull/283
> pkg(credential-helpers): match min macos version

- Makefile
- common/packages.hcl
- common/packages.mk
* follow-up https://github.com/docker/docker-ce-packaging/pull/911
> common: ubuntu 18.04 eol

- common/packages.hcl
- common/packages.mk
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
* follow-up https://github.com/docker/docker-ce-packaging/pull/928
> common: ubuntu 22.10 eol

- common/packages.hcl
- common/packages.mk
* follow-up https://github.com/docker/docker-ce-packaging/pull/894
> common: fedora 36 eol

- pkg/compose/Makefile
- pkg/compose/docker-bake.hcl
related to https://github.com/docker/compose/pull/10889
> pkg(compose): update default branch

- pkg/docker-engine/rpm/docker-ce.spec
follow-up https://github.com/docker/docker-ce-packaging/pull/852
> docker-engine: add docker.socket to %systemd_preun

- Makefile
- common/packages.hcl
- common/packages.mk
- common/scripts/rpm-builddep.sh
- pkg/buildx/Dockerfile
- pkg/compose/Dockerfile
- pkg/containerd/Dockerfile
- pkg/credential-helpers/Dockerfile
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
- pkg/sbom/Dockerfile
- pkg/scan/Dockerfile
backport of
* https://github.com/docker/packaging/pull/155
* https://github.com/docker/packaging/pull/167
* https://github.com/docker/packaging/pull/169
* https://github.com/docker/packaging/pull/166
> [containerd/1.6 backport] cherry-picks

- Makefile
- common/packages.hcl
- common/packages.mk
follow-up:
* https://github.com/docker/docker-ce-packaging/pull/1181
Also removes debian 10 and raspbian 10.
> distro: add debian 13

- .github/workflows/.build.yml
relates to https://github.com/docker/packaging/actions/runs/15658063054/job/44111899854#step:11:809
> ci(build): free disk space

- Makefile
- docker-bake.hcl
follow-up:
* https://github.com/docker/docker-ce-packaging/pull/1026
* https://github.com/docker/docker-ce-packaging/pull/1110
* https://github.com/docker/docker-ce-packaging/pull/1201
* https://github.com/docker/docker-ce-packaging/pull/1058
* https://github.com/docker/docker-ce-packaging/pull/1169
* https://github.com/docker/containerd-packaging/pull/362
* https://github.com/docker/containerd-packaging/pull/422
* https://github.com/docker/containerd-packaging/pull/418
> distro: add fedora 41 and 42

- docker-bake.hcl
- hack/scripts/rpm-init.sh
- pkg/credential-helpers/verify.Dockerfile
- pkg/docker-engine/scripts/pkg-rpm-build.sh
- pkg/docker-engine/verify.Dockerfile
Align with CE packaging:
- https://github.com/docker/docker-ce-packaging/blob/73be86c91f03f0f7e892bc9d0064a45c21c869c1/distros.json#L11-L19
> rpm: Add CentOS 10

- .github/workflows/.build.yml
relates to https://github.com/docker/packaging/issues/248#issuecomment-3201779809
> ci: fix build workflow

- docker-bake.hcl
To align with current docker-ce-packaging
> pkg(model): Add linux/arm/v7 platform

- pkg/buildx/deb/rules
- pkg/compose/deb/rules
- pkg/containerd/deb/rules
- pkg/credential-helpers/deb/rules
- pkg/docker-cli/deb/rules
- pkg/docker-engine/deb/rules
- pkg/model/deb/rules
- fixes: https://github.com/docker/containerd-packaging/issues/428
Adapted from https://github.com/docker/containerd-packaging/pull/348
> Fix Raspbian armhf

- .github/workflows/.build.yml
relates to https://github.com/docker/packaging/releases/tag/buildx%2Fv0.29.1-35
Should be:
```
* Tags
* `dockereng/packaging:buildx-v0.29.1`
* `dockereng/packaging:buildx-v0.29.1-35`
```
> build: fix tags in release body

- hack/scripts/rpm-init.sh
- hack/scripts/verify-rpm-init.sh
rockylinux repo mirrors are often out of sync so let just use the base url instead for better stability.
relates to https://github.com/docker/packaging/actions/runs/18247347856/job/51957092362#step:7:717
```
#30 [linux/amd64 builder-rpm 3/7] RUN --mount=type=bind,from=scripts,source=rpm-init.sh,target=/usr/local/bin/rpm-init     --mount=type=secret,id=RH_USER,env=RH_USER     --mount=type=secret,id=RH_PASS,env=RH_PASS     rpm-init rockylinux8
#30 101.7 Rocky Linux 8 - AppStream                        16 kB/s | 1.6 MB     01:41    
#30 101.7 Errors during downloading metadata for repository 'appstream':
#30 101.7   - Status code: 404 for http://rockylinux.mirror.intermax.nl/8.10/AppStream/x86_64/os/repodata/6af7616e8435d22ef00957a93201f142f7ac51a4dc5203fb3d29ebe417462038-filelists.xml.gz …
```
> rockylinux: disable mirrors for better stability
