docker/packaging

- .github/workflows/release.yml
- Makefile
- README.md
- pkg/buildx/Dockerfile
- pkg/buildx/Makefile
- pkg/compose/Dockerfile
- pkg/compose/Makefile
- pkg/containerd/Dockerfile
- pkg/containerd/Makefile
- pkg/credential-helpers/Dockerfile
- pkg/credential-helpers/Makefile
- pkg/docker-cli/Dockerfile
- pkg/docker-cli/Makefile
- pkg/docker-engine/Dockerfile
- pkg/docker-engine/Makefile
- pkg/sbom/Dockerfile
- pkg/sbom/Makefile
- pkg/scan/Dockerfile
- pkg/scan/Makefile
also sets additional metadata like build result, summary and packages list in release body.
preview: https://github.com/crazy-max/docker-packaging/releases/tag/buildx%2Fv0.9.1-9
> ci(release): split pkgs in dyn matrix and use remote builders

- .github/workflows/release.yml
- README.md
> ci: create draft GitHub release

- .github/workflows/release.yml
This happens for some packages like `sbom` and `scan` which do not support the `linux/arm/v7` platform and therefore `raspbian` packages will not build.
> ci(release): ignore artifacts not found

- .github/workflows/.release.yml
- README.md
new format: `nightly-<project>-<version>`
> ci(release): change nightly build tag format

- .github/workflows/.build.yml
- common/scripts/rpm-init.sh
- pkg/containerd/verify.Dockerfile
- pkg/credential-helpers/verify.Dockerfile
- pkg/docker-cli/verify.Dockerfile
- pkg/docker-engine/verify.Dockerfile
Encounter this issue with containerd package:
```
#64 4.382 ================================================================================
#64 4.382  Package              Arch   Version             Repository                Size
#64 4.382 ================================================================================
#64 4.382 Installing:
#64 4.382  btrfs-progs-devel    x86_64 4.9.1-1.0.2.el7     ol7_optional_latest       46 k
#64 4.382  devtoolset-4-gcc     x86_64 5.3.1-6.1.el7       ol7_software_collections  26 M
#64 4.382  libseccomp-devel     x86_64 2.3.1-4.el7         ol7_optional_latest       63 k
#64 4.382  libtool-ltdl-devel   x86_64 2.4.2-22.el7_3      ol7_latest               167 k
#64 4.382  make                 x86_64 1:3.82-24.el7       ol7_latest               420 k
#64 …
```
> common: remove software collections repo when Git installed

- pkg/docker-engine/scripts/pkg-static-build.sh
related to https://github.com/moby/moby/pull/43762
last nightly build failed with: https://github.com/docker/packaging/actions/runs/3213097052/jobs/5276739551#step:7:2616
```
#0 0.995 cmd/dockerd/config.go
#0 0.996 cmd/dockerd/config_windows.go
#0 0.997 cmd/dockerd/daemon.go
#0 0.997 cmd/dockerd/daemon_test.go
#0 0.997 cmd/dockerd/daemon_windows.go
#0 0.998 cmd/dockerd/docker.go
#0 0.998 cmd/dockerd/docker_windows.go
#0 0.998 cmd/dockerd/genwinres_windows.go
#0 1.001 2022/10/11 07:42:18 open ../../cli/winresources/dockerd/winres.json: no such file or directory
#0 1.007 cmd/dockerd/genwinres_windows.go:1: running "go-winres": exit status 1
```
@thaJeztah Could you backport https://github.com/moby/moby/pull/43762 to 22.06 maybe?
> pkg(docker-engine): BINARY_SHORT_NAME deprecated

- pkg/containerd/Dockerfile
- pkg/containerd/Makefile
- pkg/containerd/deb/changelog
- pkg/containerd/docker-bake.hcl
- pkg/containerd/rpm/containerd.spec
- relates to https://github.com/docker/containerd-packaging/pull/304
release notes: https://github.com/containerd/containerd/releases/tag/v1.6.15
> Welcome to the v1.6.15 release of containerd!
>
> The fifteenth patch release for containerd 1.6 fixes an issue with CNI in the CRI plugin
>
> Notable Updates
>
> - Fix no CNI info for pod sandbox on restart in CRI plugin
full diff: https://github.com/containerd/containerd/compare/v1.6.14...v1.6.15
> pkg(containerd): update to 1.6.15

- .github/workflows/release-buildx.yml
- .github/workflows/release-compose.yml
- .github/workflows/release-containerd.yml
- .github/workflows/release-credential-helpers.yml
- .github/workflows/release-docker-cli.yml
- .github/workflows/release-docker-engine.yml
- .github/workflows/release-sbom.yml
- .github/workflows/release-scan.yml
- pkg/buildx/Makefile
- pkg/buildx/docker-bake.hcl
- pkg/compose/Dockerfile
- pkg/compose/Makefile
- pkg/compose/docker-bake.hcl
- pkg/containerd/Dockerfile
- pkg/containerd/Makefile
- pkg/containerd/docker-bake.hcl
- pkg/credential-helpers/Makefile
- pkg/credential-helpers/docker-bake.hcl
- pkg/docker-cli/Dockerfile
- pkg/docker-cli/Makefile
- pkg/docker-cli/docker-bake.hcl
- pkg/docker-engine/Dockerfile
- pkg/docker-engine/Makefile
- pkg/docker-engine/docker-bake.hcl
- pkg/docker-engine/scripts/pkg-rpm-build.sh
- pkg/sbom/Makefile
- pkg/sbom/docker-bake.hcl
- pkg/scan/Makefile
- pkg/scan/docker-bake.hcl
Use default branch when building packages and requires a ref (version) to be set when creating a release.
> pkg: use default branch

- .github/workflows/nightly.yml
- .github/workflows/release-buildx.yml
- .github/workflows/release-compose.yml
- .github/workflows/release-containerd.yml
- .github/workflows/release-credential-helpers.yml
- .github/workflows/release-docker-cli.yml
- .github/workflows/release-docker-engine.yml
- .github/workflows/release-sbom.yml
- .github/workflows/release-scan.yml
Removes cron from release workflow for each package and create a dedicated nightly workflow instead. This will avoid having the `run_number` in [GitHub Releases](https://github.com/docker/packaging/releases) being incremented for every nighty and release build:
https://github.com/docker/packaging/blob/71f00b0e2e09546db3d8bbbcca776f1238015bc6/.github/workflows/.release.yml#L224
> ci: created dedicated nightly workflow

- pkg/credential-helpers/verify.Dockerfile
follow-up #83 
Disable `epel` repo to avoid issue with `pass` package on CentOS 9.
> pkg(credential-helpers): disable epel-release on centos 9

- README.md
- common/build.mk
Similar to https://github.com/moby/buildkit/pull/3469
https://github.com/docker/packaging/actions/runs/4034501647/jobs/6935765384#step:7:1410
```
#35 1609.6 make[1]: Entering directory '/root/package'
#35 1609.6 ver="$(/usr/libexec/docker/cli-plugins/docker-buildx docker-cli-plugin-metadata | awk '{ gsub(/[",:]/,"")}; $1 == "Version" { print $2 }')"; \
#35 1609.6 	test "$ver" = "v0.0.0-20230126185721-a718d07" && echo "PASS: docker-buildx version OK" || (echo "FAIL: docker-buildx version ($ver) did not match" && exit 1)
#35 1610.0 Illegal instruction (core dumped)
```
> common: pin busybox tag

- .github/workflows/.release.yml
- .github/workflows/nightly.yml
fixes https://github.com/docker/packaging/actions/runs/4154080256/jobs/7186333348#step:10:184
```
/usr/bin/docker buildx bake --file ./docker-bake.hcl --file /tmp/docker-metadata-action-7H7B93/docker-metadata-action-bake.json --set *.output=type=image,push=true --metadata-file /tmp/docker-build-push-T6xmKB/metadata-file release
ERROR: invalid tag "dockereng/packaging:-5": invalid reference format
Error: buildx bake failed with: ERROR: invalid tag "dockereng/packaging:-5": invalid reference format
```
Also fixes env vars not being propagated. This is a known limitation with reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations
> ci: fix release workflow

- pkg/containerd/Dockerfile
- pkg/containerd/deb/control
- pkg/containerd/rpm/containerd.spec
- pkg/containerd/scripts/pkg-rpm-build.sh
> pkg: containerd now depends on kernel headers instead of libbtrfs

- .github/workflows/.build.yml
- .github/workflows/.release.yml
- .github/workflows/nightly.yml
- .github/workflows/release-buildx.yml
- .github/workflows/release-compose.yml
- .github/workflows/release-containerd.yml
- .github/workflows/release-credential-helpers.yml
- .github/workflows/release-docker-cli.yml
- .github/workflows/release-docker-engine.yml
- .github/workflows/release-sbom.yml
- .github/workflows/release-scan.yml
Saw this in nightly build workflow:
```
Invalid workflow file: .github/workflows/nightly.yml#L22
The workflow is not valid. .github/workflows/nightly.yml (Line: 22, Col: 12): Unrecognized named-value: 'env'. Located at position 1 within expression: env.NIGHTLY_BUILD .github/workflows/nightly.yml (Line: 31, Col: 12): Unrecognized named-value: 'env'. Located at position 1 within expression: env.NIGHTLY_BUILD
```
Seems GitHub made `env` key reserved recently.
> ci: fix env key in reusable workflows

- pkg/docker-engine/deb/rules
- pkg/docker-engine/rpm/docker-ce.spec
See https://github.com/moby/moby/commit/6caaa8cadc9e4f1e122b7b2bb4451500bbec6086 / https://github.com/moby/moby/pull/45198 / https://github.com/docker/docker-ce-packaging/pull/868
> Move "docker-init" into appropriate "libexec" directory

- pkg/docker-cli/deb/control
- pkg/docker-cli/rpm/docker-ce-cli.spec
* backport of https://github.com/docker/packaging/pull/116
> [docker/23.0 backport] pkg(docker-cli): remove scan plugin from recommends

- pkg/docker-cli/Makefile
- pkg/docker-cli/docker-bake.hcl
- pkg/docker-engine/Makefile
- pkg/docker-engine/docker-bake.hcl
created https://github.com/docker/packaging/tree/docker/24.0 branch so enforce default ref to `24.0`
> [docker/24.0] pkg(docker-cli,docker-engine): fix default ref to 24.0

- pkg/containerd/Makefile
- pkg/containerd/docker-bake.hcl
created https://github.com/docker/packaging/tree/container/1.7 branch so enforce default ref to `1.7`
> [containerd/1.7] pkg(containerd): fix default ref to release/1.7

- .github/workflows/.release.yml
- pkg/buildx/Makefile
- pkg/compose/Makefile
- pkg/containerd/Makefile
- pkg/credential-helpers/Makefile
- pkg/docker-cli/Makefile
- pkg/docker-engine/Makefile
Our remote instance seems offline for quite some time. Let's disable release builds for this arch for now.
> disable s390x releases

- pkg/compose/Dockerfile
Found this issue in CI: https://github.com/docker/packaging/actions/runs/5758467430/job/15611066955#step:8:4656
```
------
> [linux/amd64 builder-static-nosdk 6/6] RUN --mount=type=bind,source=scripts/pkg-static-build.sh,target=/usr/local/bin/pkg-static-build     --mount=type=bind,from=common-scripts,source=gen-ver.sh,target=/usr/local/bin/gen-ver     --mount=type=bind,from=common-scripts,source=fix-cc.sh,target=/usr/local/bin/fix-cc     --mount=type=bind,from=src,source=/src,target=/usr/local/src/compose     --mount=type=bind,from=gocross,source=/usr/local/go,target=/usr/local/go,rw     OUTDIR=/out BUILDDIR=/build SRCDIR=/usr/local/src/compose pkg-static-build:
827.3 github.com/buger/goterm: mkdir /tmp/go-build3973811788/b1013/: no space left on device
827.3 github.com/mattn/go-isatty: …
```
> pkg(compose): fix go modules download for static pkg

- pkg/buildx/Dockerfile
- pkg/compose/Dockerfile
- pkg/containerd/Dockerfile
- pkg/credential-helpers/Dockerfile
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
- pkg/sbom/Dockerfile
- pkg/scan/Dockerfile
found this issue when building docker-engine on Oracle Linux 9: https://github.com/docker/packaging/actions/runs/5770498207/job/15643601286#step:7:1478
```
#33 [linux/amd64 builder-rpm 5/7] RUN <<EOT (set -e...)
#33 11.26 Oracle Linux 9 BaseOS Latest (x86_64)            49 kB/s | 3.6 kB     00:00    
#33 11.43 Oracle Linux 9 Application Stream Packages (x86  55 kB/s | 3.9 kB     00:00    
#33 11.88 Oracle Linux 9 Addons (x86_64)                  868 kB/s | 286 kB     00:00    
#33 12.56 Oracle Linux 9 CodeReady Builder (x86_64) - (Un  15 MB/s | 5.6 MB     00:00    
#33 16.17 Package bash-5.1.8-6.el9_1.x86_64 is already installed.
#33 16.17 Package bash-5.1.8-6.el9_1.x86_64 is already installed.
#33 16.17 Package ca-certificates-2022.2.54-90.2.el9_0.noarch is already installed.
#33 16.17 …
```
> rpm: set nobest flag for dnf builddep command

- .github/workflows/manual-build.yml
- .github/workflows/nightly.yml
Remote arm64 BuildKit instance can't keep up if we run hundreds of builds in //.
> ci: set max-parallel to 1 for release builds

- Makefile
- common/packages.hcl
- common/packages.mk
follow-up https://github.com/docker/docker-ce-packaging/pull/940
> distro: add fedora 39

- pkg/docker-engine/rpm/docker-ce.spec
follow-up https://github.com/docker/docker-ce-packaging/pull/945
> docker-engine: fix require with rpm "docker-ce-rootless-extras" pkg

- Makefile
- common/packages.hcl
- common/packages.mk
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
relates to https://github.com/docker/docker-ce-packaging/pull/949
relates to https://github.com/docker/containerd-packaging/commit/68ea3734399c7701623f94d3c88794117185d8bb - https://github.com/docker/containerd-packaging/pull/328
Ubuntu 23.10 is planned to be released on October 12, 2023, but final betas are available now.
> distro: add ubuntu 23.10

- Makefile
- common/packages.hcl
- common/packages.mk
- pkg/containerd/Dockerfile
- pkg/credential-helpers/Dockerfile
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
- pkg/docker-engine/rpm/docker-ce.spec
backport of
* https://github.com/docker/packaging/pull/167
* https://github.com/docker/packaging/pull/169
* https://github.com/docker/packaging/pull/170
* https://github.com/docker/packaging/pull/171
* https://github.com/docker/packaging/pull/166
> [docker/24.0 backport] cherry-picks

- Makefile
- common/packages.hcl
- common/packages.mk
- pkg/containerd/Dockerfile
- pkg/credential-helpers/Dockerfile
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
backport of
* https://github.com/docker/packaging/pull/167
* https://github.com/docker/packaging/pull/169
* https://github.com/docker/packaging/pull/166
> [containerd/1.7 backport] cherry-picks

- pkg/containerd/Dockerfile
- pkg/containerd/Makefile
- pkg/containerd/docker-bake.hcl
Also align go-md2man version with the one from release/1.6 branch.
> [containerd/1.6] bump go to 1.20.8

- .github/workflows/nightly.yml
- Makefile
Exclude `sbom` and `scan` packages from being built in the nightly workflow. Also update minimal GHA matrix.
> ci(nightly): exclude deprecated packages

- pkg/docker-cli/deb/control
- pkg/docker-cli/rpm/docker-ce-cli.spec
- pkg/docker-engine/deb/control
- pkg/docker-engine/rpm/docker-ce.spec
- relates to https://github.com/docker/docker-ce-packaging/pull/1019
This was added in [docker@a15b67b1affb2eac5365614e55703f43b6f73e9b] (2015),
at which time this package was already deprecated / replaced:
> Add old docker-engine-cs name to package conflicts
[docker@a15b67b1affb2eac5365614e55703f43b6f73e9b]: https://github.com/moby/moby/commit/a15b67b1affb2eac5365614e55703f43b6f73e9b
These conflicts were added as part of the first implementation of the deb
packaging scripts in [docker@eee1efcfd6c46dbdc5da02ca12722e399a56bb12] (2015)
to replace the old packages. These packages where part of the old PPA at
get.docker.io (see [1], [2]), which is long gone;
curl -I https://get.docker.io/ubuntu
HTTP/1.1 301 Moved Permanently
content-length: 0
location: https://get.docker.com/ubuntu
curl -fsSL …
> docker-cli, docker-engine: remove outdated "conflicts

- .github/workflows/.build.yml
- .github/workflows/.release.yml
- .github/workflows/manual-build.yml
- .github/workflows/nightly.yml
- .github/workflows/validate.yml
- README.md
- common/build.mk
- pkg/buildx/Makefile
- pkg/buildx/docker-bake.hcl
- pkg/compose/Makefile
- pkg/compose/docker-bake.hcl
- pkg/containerd/Makefile
- pkg/containerd/docker-bake.hcl
- pkg/credential-helpers/Makefile
- pkg/credential-helpers/docker-bake.hcl
- pkg/docker-cli/Makefile
- pkg/docker-cli/docker-bake.hcl
- pkg/docker-engine/Makefile
- pkg/docker-engine/docker-bake.hcl
- pkg/sbom/Makefile
- pkg/sbom/docker-bake.hcl
- pkg/scan/Makefile
- pkg/scan/docker-bake.hcl
> ci: update runner to ubuntu-24.04 and bake action to v6

- pkg/containerd/Dockerfile
- pkg/containerd/docker-bake.hcl
- pkg/containerd/scripts/pkg-static-build.sh
relates to https://github.com/docker/packaging/actions/runs/15518358502/job/43688269359#step:8:2517
```
> [linux/amd64->arm/v7 builder-static 6/6] RUN --mount=type=bind,source=scripts/pkg-static-build.sh,target=/usr/local/bin/pkg-static-build     --mount=type=bind,from=common-scripts,source=gen-ver.sh,target=/usr/local/bin/gen-ver     --mount=type=bind,from=common-scripts,source=fix-cc.sh,target=/usr/local/bin/fix-cc     --mount=type=bind,from=src,source=/src,target=/go/src/github.com/containerd/containerd,rw     --mount=type=bind,from=runc-src,source=/src,target=/go/src/github.com/opencontainers/runc,rw     --mount=type=bind,from=gocross,source=/usr/local/go,target=/usr/local/go,rw     OUTDIR=/out BUILDDIR=/build SRCDIR=/go/src/github.com/containerd/containerd …
```
> pkg(containerd): build libseccomp from source

- Makefile
- common/packages.hcl
- common/packages.mk
- pkg/docker-cli/Dockerfile
- pkg/docker-engine/Dockerfile
follow-up:
* https://github.com/docker/docker-ce-packaging/pull/1006
* https://github.com/docker/docker-ce-packaging/pull/1200
Also removes ubuntu 20.04.
> distro: add ubuntu 24.04

- pkg/containerd/rpm/containerd.spec
follow-up:
* https://github.com/docker/containerd-packaging/pull/367
relates to https://github.com/docker/packaging/actions/runs/15822270439/job/44594051089?pr=222#step:7:1794
```
#40 0.299 + rpmbuild --target x86_64 -bb --define '_version 0.0.0~20250622010009~9300d03' --define '_origversion v0.0.0-20250622010009-9300d03' --define '_release 0' --define '_commit 9300d03899283ac9c8a88d451fb12aadb42fd77f' /root/rpmbuild/SPECS/containerd.spec
#40 0.306 Building target platforms: x86_64
#40 0.306 Building for target x86_64
#40 0.309 warning: line 38: It's not recommended to have unversioned Obsoletes: Obsoletes: containerd
#40 0.309 warning: line 39: It's not recommended to have unversioned Obsoletes: Obsoletes: runc
#40 0.322 setting SOURCE_DATE_EPOCH=1675036800
#40 0.332 …
```
> pkg(containerd): update macros used in rpm spec

- pkg/buildx/deb/rules
- pkg/compose/deb/rules
- pkg/containerd/deb/rules
- pkg/containerd/rpm/containerd.spec
- pkg/credential-helpers/deb/rules
- pkg/docker-cli/deb/docker-ce-cli.bash-completion
- pkg/docker-cli/deb/rules
- pkg/docker-cli/rpm/docker-ce-cli.spec
- pkg/docker-cli/scripts/pkg-deb-build.sh
- pkg/docker-engine/deb/rules
- pkg/docker-engine/rpm/docker-ce.spec
- pkg/sbom/deb/rules
- pkg/scan/deb/rules
follow-up:
* https://github.com/docker/docker-ce-packaging/pull/1154
> deb, rpm: slight refactor and cleanup

- docker-bake.hcl
follow-up https://github.com/docker/packaging/pull/230#discussion_r2185654422
> chore: use permalinks

- pkg/compose/scripts/pkg-deb-build.sh
- pkg/model/scripts/pkg-deb-build.sh
Standardize package filename format to include distribution information for docker-model-plugin and docker-compose-plugin packages.
Before this change, model plugin filenames didn't have distro information:
```diff
-docker-model-plugin_0.1.36-0_arm64.deb
+docker-model-plugin_0.1.36-0~debian.12~bookworm_arm64.deb
```
> deb: use gen-deb-changelog for model and compose

- docker-bake.hcl
alternative to and closes #245
> Add TEST_ONLY build arg for each distro

- .github/workflows/.build.yml
Fix `ERROR: failed to solve: non-bool value specified for push: strconv.ParseBool: parsing "draft": invalid syntax`   
https://github.com/docker/packaging/actions/runs/17164640078/job/48702246917#step:11:407
> gha/build: fix release condition for Docker image push

- docker-bake.hcl
This will require first this containerd-packaging pull request to be merged and that an actual fedora 43 rpm for containerd is created before being able to merge this: https://github.com/docker/containerd-packaging/pull/427
> Add Fedora 43.

- .github/workflows/.build.yml
To easily get the image reference to use with the release pipeline
> gha/build: Show tags in the summary

- pkg/compose/rpm/docker-compose-plugin.spec
It's no longer a part of the compose source code
https://github.com/docker/compose/commit/a429c09dfa84d22262a9a69406eff5841fd9bdb3
> rpm/compose: Remove MAINTAINERS docs file

- .github/workflows/release-buildx.yml
- .github/workflows/release-compose.yml
- .github/workflows/release-containerd.yml
- .github/workflows/release-credential-helpers.yml
- .github/workflows/release-docker-cli.yml
- .github/workflows/release-docker-engine.yml
- .github/workflows/release-model.yml
Require an explicit choice to create a Github release
> gha/release: default to pushonly

- .github/workflows/.build.yml
- .github/workflows/release-buildx.yml
- .github/workflows/release-compose.yml
- .github/workflows/release-containerd.yml
- .github/workflows/release-credential-helpers.yml
- .github/workflows/release-docker-cli.yml
- .github/workflows/release-docker-engine.yml
- .github/workflows/release-model.yml
Add optional distro input parameter to all release workflows and the reusable build workflow to allow building packages for a specific distribution only.
This is useful when backfilling packages for a new distro.
> gha/build: Support building only single distro

- docker-bake.hcl
relates to https://github.com/docker/packaging/actions/runs/18190773894/job/51785266600?pr=258#step:7:1494
```
0.272 GO111MODULE=on go build  -trimpath -tags "e2e" -ldflags "-w -X github.com/docker/compose/v2/internal.Version=v0.0.0-20250930100346-fa08127" -o "./bin/docker-compose" ./cmd
0.279 go: go.mod requires go >= 1.24.7 (running go 1.23.12; GOTOOLCHAIN=local)
0.279 make: *** [Makefile:61: build] Error 1
0.280 error: Bad exit status from /var/tmp/rpm-tmp.Qtklvx (%build)
0.280     Bad exit status from /var/tmp/rpm-tmp.Qtklvx (%build)
0.280 
0.280 
0.280 RPM build errors:
```
> update go version for compose and credential-helpers pkgs
